version: 1.0.4
description: UPF initial local configuration

# PFCP Configuration
# The listen IP and nodeID of the N4 interface on this UPF (Can't set to 0.0.0.0)
pfcp:
  addr: 127.0.0.8   # IP addr for listening
  nodeID: 127.0.0.8 # External IP or FQDN can be reached
  retransTimeout: 1s # retransmission timeout
  maxRetrans: 3 # the max number of retransmission

# GTP-U Configuration
gtpu:
  forwarder: gtp5g
  # The IP list of the N3/N9 interfaces on this UPF
  # You can bind this to a specific IP from your available subnets (e.g., 10.10.0.1).
  # Alternatively, you can bind it to all interfaces using 0.0.0.0.
  # If you bind to a specific IP, ensure SMF uses the same IP in its N3 configuration.
  # If you bind to all (0.0.0.0), SMF can use any of the available UPF IPs, but do not use 0.0.0.0 in SMF.
  ifList:
    - addr: 140.113.208.88
      type: N3
    - addr: 127.0.0.8
      type: N3
      # name: upf.5gc.nctu.me
      # ifname: gtpif
      # mtu: 1400

# SBI Configuration
sbi:
  scheme: http # the protocol for sbi (http or https)
  registerIp: 127.0.0.8 # IP used to register to NRF, support IPv4 only
  bindingIp: 127.0.0.8  # IP used to bind the service, support IPv4 only
  port: 8000 # port used to bind the service
  tls: # the local path of TLS key
    pem: cert/upf.pem # AMF TLS Certificate
    key: cert/upf.key # AMF TLS Private key
  nrfUri: http://127.0.0.10:8000 # NRF URI

# Supported DNNs
# List of Data Network Names (DNN) supported by this UPF.
dnnList:
  - dnn: internet # Data Network Name
    cidr: 10.60.0.0/16 # Classless Inter-Domain Routing for assigned IPv4 pool of UE
  - dnn: internet # Data Network Name
    cidr: 10.61.0.0/16 # Classless Inter-Domain Routing for assigned IPv4 pool of UE
    # natifname: eth0

# Logging Configuration
# Controls logging level and output for the UPF.
logger:
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
